docker:
  image: yegor256/rultor-image
install: |-
  export LC_ALL=en_US.UTF-8
  export LANG=en_US.UTF-8
  export LANGUAGE=en_US.UTF-8
merge:
  script: |-
    export PATH=/usr/local/bin:$PATH
    npm install
    npm run build
deploy:
  script: |-
    echo There is nothing to deploy
    exit 1
release:
  script: |-
    npm run build
    npm run prod
