docker:
  image: yegor256/rultor-image
install: |-
  npm i
  export PATH=$PATH:/usr/lib/postgresql/10/bin
  export LC_ALL=en_US.UTF-8
  export LANG=en_US.UTF-8
  export LANGUAGE=en_US.UTF-8
merge:
  script: |-
    docker-compose up -d postgres
    docker-compose build
deploy:
  script: |-
    echo There is nothing to deploy
    exit 1
