readers:
  - "urn:github:526301"
assets:
  config.yml: yegor256/home#assets/codexia/config.yml
  id_rsa: yegor256/home#assets/heroku-key
  id_rsa.pub: yegor256/home#assets/heroku-key.pub
install: |-
  export PATH=$PATH:/usr/lib/postgresql/10/bin
  sudo apt-get -y update
  sudo apt-get -y install libpq-dev
  git config --global user.email "server@codexia.org"
  git config --global user.name "codexia.org"
  sudo gem update bundler
  sudo bundle install --no-color "--gemfile=$(pwd)/Gemfile"
release:
  sensitive:
    - config.yml
  script: |-
    pdd -f /dev/null
    export GEM_HOME=~/.ruby
    export GEM_PATH=$GEM_HOME:$GEM_PATH
    ruby -v
    bundle exec rake
    git remote add dokku dokku@dokku.codexia.org:codexia
    rm -rf ~/.ssh
    mkdir ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    git fetch
    sed -i "s/0\.0\.0/${tag}/g" ./version.rb
    release=$(git rev-parse --short HEAD)
    sed -i "s/000000/${release}/g" ./version.rb
    git add ./version.rb
    git commit -m 'build number set'
    cp ../config.yml config.yml
    bundle exec rake config
    git add config.yml
    git commit -m 'config.yml'
    git push -f dokku $(git symbolic-ref --short HEAD):master
    git reset HEAD~1
    rm -f target/pgsql-config.yml
    bundle exec rake liquibase
    rm -rf config.yml
    curl -f --connect-timeout 15 --retry 5 --retry-delay 30 https://www.codexia.org > /dev/null
  commanders:
  - yegor256
architect:
- yegor256
merge:
  commanders: []
  script: |-
    pdd -f /dev/null
    bundle exec rake
deploy: {}
