language: node_js
node_js:
  - lts/*
services:
  - docker
install: |-
  npm ci
  npm install -g codecov
  docker-compose up -d postgres
  docker-compose build
script: |-
  set -e
  docker-compose up app
  ./node_modules/.bin/nyc report --reporter=lcov
  codecov
  log=$(git log $TRAVIS_COMMIT_RANGE --oneline)
  echo $'Commit message: '$TRAVIS_COMMIT_MESSAGE
  echo $'**Change log:**<br/>'${log//$'\n'/<br/>}
branches:
  only:
    - master
