language: node_js
node_js:
- lts/*
install: |-
  npm ci
  npm install -g codecov
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5432
  - PGUSER=user
  - PGPASSWORD=1234
  - PGDB=db
script: |-
  set -e
  npm run build
  ./node_modules/.bin/nyc report --reporter=lcov
  codecov
  log=$(git log $TRAVIS_COMMIT_RANGE --oneline)
  echo $'Commit message: '$TRAVIS_COMMIT_MESSAGE
  echo $'**Change log:**<br/>'${log//$'\n'/<br/>}
branches:
  only:
  - master
